version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: recharts
    versions:
    - 2.0.4
    - 2.0.6
    - 2.0.7
    - 2.0.8
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
