name: Publish Docker
on: 
  release:
  push:
    types: 
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: akkeris/ui
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_names: true
